-- ============================================================================
-- Database Systems Lab — Transactions
-- File   : sql/transactions.sql
-- Run after schema.sql and sample_data.sql have been loaded.
--
-- Demonstrates a multi-statement transaction that must keep products.stock
-- and the orders/order_items tables consistent with each other: stock is
-- decremented and the order is recorded atomically, so a crash or error
-- partway through can never leave stock reduced without a matching order,
-- or an order recorded without the stock having been reserved.
-- ============================================================================

PRAGMA foreign_keys = ON;


-- ============================================================================
-- Example 1: Successful order — BEGIN ... COMMIT
--
-- Customer 3 (Wei Chen) orders 2 units of product 3 (USB-C Hub, id 3).
-- ============================================================================
BEGIN TRANSACTION;

-- Step 1: Reserve stock. The WHERE clause guards against overselling: the
-- UPDATE only matches (and only decrements) the row if enough stock exists.
UPDATE products
SET stock_quantity = stock_quantity - 2
WHERE product_id = 3
  AND stock_quantity >= 2;

-- Step 2: Create the order header for this customer.
INSERT INTO orders (customer_id, order_date, status, shipping_address)
VALUES (3, datetime('now'), 'pending', '7 Birch Court, Seattle, WA 98101');

-- Step 3: Attach the line item to the order we just created. last_insert_rowid()
-- returns the order_id generated by the INSERT in Step 2, so no separate
-- lookup query is needed to link the two rows correctly.
INSERT INTO order_items (order_id, product_id, quantity, unit_price)
VALUES (last_insert_rowid(), 3, 2, 34.50);

-- Both the stock adjustment and the new order/order_item rows become
-- permanent together, or not at all.
COMMIT;


-- ============================================================================
-- Example 2: Failed order — BEGIN ... ROLLBACK
--
-- Customer 6 (Priya Sharma) tries to order 9999 units of product 7
-- (Notebook Set), far more than are in stock. The guarded UPDATE in Step 1
-- matches zero rows, so we roll the whole transaction back instead of
-- inserting an order for stock that was never actually reserved.
-- ============================================================================
BEGIN TRANSACTION;

UPDATE products
SET stock_quantity = stock_quantity - 9999
WHERE product_id = 7
  AND stock_quantity >= 9999;
-- changes() reports how many rows the statement above affected. In a driver
-- (Python's sqlite3, etc.) you would inspect cursor.rowcount / changes()
-- right here and branch: 0 -> ROLLBACK, >0 -> continue to INSERT + COMMIT.
-- This script hard-codes the "insufficient stock" outcome to demonstrate
-- the ROLLBACK path explicitly:

ROLLBACK;

-- After the ROLLBACK, product 7's stock_quantity is unchanged and no order
-- or order_item rows exist for this attempt — the transaction left no trace.


-- ============================================================================
-- When to ROLLBACK instead of COMMIT (general guidance, not SQLite-specific)
-- ============================================================================
-- Roll back whenever any statement inside the transaction fails a business
-- rule or a database constraint, including:
--   - A guarded UPDATE affects 0 rows (as in Example 2) -- the precondition
--     (enough stock, correct current status, etc.) was not met.
--   - A statement raises a constraint violation: FOREIGN KEY, CHECK, UNIQUE,
--     or NOT NULL (e.g. inserting an order_item for a product_id that does
--     not exist, or a negative quantity).
--   - Application-level validation fails between statements (e.g. a payment
--     authorization call to an external service returns "declined" after
--     stock was tentatively reserved but before the order is finalized).
--   - Any statement in the sequence raises an unexpected exception/error --
--     the safe default is to roll back rather than commit a partial change.
-- The whole point of wrapping the UPDATE + INSERT + INSERT in one
-- transaction is atomicity: readers must never observe stock that has been
-- decremented without a corresponding order, or an order that references
-- stock that was never actually reserved.


-- ============================================================================
-- A note on isolation levels
-- ============================================================================
-- SQLite does not expose configurable ANSI isolation levels (READ COMMITTED,
-- REPEATABLE READ, SERIALIZABLE, etc.) the way client/server engines such as
-- PostgreSQL or MySQL do. Instead:
--   - Every SQLite transaction is effectively SERIALIZABLE: a writer takes a
--     lock on the whole database file (or, in WAL mode, gets a consistent
--     snapshot of it) for the duration of the transaction, so other writers
--     block until it commits or rolls back.
--   - PRAGMA read_uncommitted can relax isolation between separate
--     connections that share the same in-process cache, but this is a rare,
--     advanced setting and is left at its default (off) here.
--   - BEGIN DEFERRED (the default used above) postpones taking any lock
--     until the first read/write actually happens. BEGIN IMMEDIATE takes a
--     write lock right away (useful when you know you are about to write
--     and want to fail fast on contention instead of deadlocking later).
--     BEGIN EXCLUSIVE takes the strongest lock, blocking other readers too.
-- In multi-user client/server databases (PostgreSQL, MySQL/InnoDB, SQL
-- Server), the equivalent concern is choosing an isolation level: READ
-- COMMITTED is the common default and prevents dirty reads but still allows
-- non-repeatable reads and phantom rows; REPEATABLE READ and SERIALIZABLE
-- add stronger guarantees at the cost of more blocking/retries. The stock
-- decrement pattern in Example 1 (UPDATE ... WHERE stock_quantity >= N) is a
-- portable way to prevent overselling even under READ COMMITTED, because the
-- row-level check and the write happen atomically in a single statement.
